include:
  - apps/adguard/compose.yaml
  - apps/aiolists/compose.yaml
  - apps/aiometadata/compose.yaml
  - apps/aiostreams/compose.yaml
  - apps/authelia/compose.yaml
  - apps/bazarr/compose.yaml
  - apps/beszel/compose.yaml
  - apps/cloudflare-ddns/compose.yaml
  - apps/comet/compose.yaml
  - apps/crowdsec/compose.yaml
  - apps/decypharr/compose.yaml
  - apps/dozzle/compose.yaml
  - apps/flaresolverr/compose.yaml
  - apps/honey/compose.yaml
  - apps/huntarr/compose.yaml
  - apps/jellyfin/compose.yaml
  - apps/mediaflow-proxy/compose.yaml
  - apps/mediafusion/compose.yaml
  - apps/portainer/compose.yaml
  - apps/prowlarr/compose.yaml
  - apps/radarr/compose.yaml
  - apps/recyclarr/compose.yaml
  - apps/searxng/compose.yaml
  - apps/seerr/compose.yaml
  - apps/sonarr/compose.yaml
  - apps/streamystats/compose.yaml
  - apps/stremthru/compose.yaml
  - apps/tmdb-addon/compose.yaml
  - apps/tmdb-collections/compose.yaml
  - apps/traefik/compose.yaml
  - apps/uptime-kuma/compose.yaml
  - apps/vaultwarden/compose.yaml
  - apps/warp/compose.yaml
  - apps/watchtower/compose.yaml
  - apps/yamtrack/compose.yaml
  - apps/zilean/compose.yaml
networks:
  default:
    name: ${DOCKER_NETWORK:-aio_default}
    external: ${DOCKER_NETWORK_EXTERNAL:-false}
